language: java
before_install:
 - chmod +x gradlew
jdk:
  - oraclejdk8
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
script:
  - ./gradlew clean check
  - ./gradlew codeCoverageReport
after_success:
  - bash <(curl -s https://codecov.io/bash)