language: java
before_install:
 - chmod +x gradlew
jdk:
  - oraclejdk8
services:
  - mysql
before_install:
  - mysql -e 'DROP DATABASE IF EXISTS meld;
               CREATE DATABASE meld DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;'

script:
  - ./gradlew clean test
  - ./gradlew codeCoverageReport
after_success:
  - bash <(curl -s https://codecov.io/bash)